# Site settings
title: Codelab42
email: info@codelab42.com
description: > # this means to ignore newlines until "baseurl:"
  The answer to your Drupal needs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.codelab42.com" # the base hostname & protocol for your site
twitter_username: codelab42
github_username:  codelab42

# Build settings
markdown: kramdown
